name: Setup
description: setup to run any scripts

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v6

    - name: Use nodejs
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
