name: 'Build Cache'
description: Cache build artifacts and dependencies

runs:
  using: 'composite'
  steps:
    - name: Cache build artifacts
      uses: actions/cache@v4
      with:
        path: dist
        key: build-${{ github.run_id }}-${{ github.sha }}
        restore-keys: |
          build-${{ github.run_id }}-
          build-
      continue-on-error: true
