name: build

on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, synchronize, reopened]

# Enabled permissions on GITHUB_TOKEN
permissions:
  # To be able to push to the repo
  contents: write
  # To update the pr description with canary info
  pull-requests: write
  # For pr-check to create a status
  statuses: write
  # Needed to create PR statuses/checks
  checks: write
  # To post comments on PRs
  issues: write

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN  }}
  PROTECTED_BRANCH_REVIEWER_TOKEN: ${{ secrets.GH_TOKEN }}
  # PR: ${{ steps.PR.outputs.number }}

jobs:
  # Run install in one step so deps can be cached for other steps
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4
      - name: Prepare repository
        run: git fetch --unshallow --tags
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/build-cache
      - run: yarn build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/build-cache
      - name: Prepare repository
        run: git fetch --unshallow --tags
      - run: yarn test

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' || (!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci'))
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/build-cache
      - name: Prepare repository
        run: git fetch --unshallow --tags
      - name: Create Release
        run: yarn auto shipit -vv
        if: env.GITHUB_TOKEN != ''
